### ISSUE TITLE
Mouse distractor

### ISSUE THREAD

**Issue by OpenSourceCS** [MaxXor/xRAT#101]
add a feature to keep the mouse moving continuously to random locations or place it at a specified position for a long time.
This is possible using Mouse Hook which is really simple

 >Please add this feature.
 >It can be used to play pranks and have fun

**Comment by DragonzMaster** [comment]
there are more important stuff to  do insteed of playing
if all these important things have been done so you can think in trolling and fun stuff

**Comment by OpenSourceCS** [comment]
I can't make out what u mean. Please be elaborate

**Comment by yankejustin** [comment]
I'd like to just ask to not reference unrelated issues because it makes it hard for many of us to resolve this issues when they are referenced in random areas. :(
I have to agree with @DragonzMaster . This Remote Administration Tool should certainly be for remote administration. Personally, I have very low interest in creating an application that is solely to cause frustration to someone else...

**Comment by yankejustin** [comment]
Just to clarify, I think this feature should be in a branch separate from this project.

**Comment by MaxXor** [comment]
Please only suggest useful features, not for trolling. :)
