### ISSUE TITLE
Quasar Update

### ISSUE THREAD

**Issue by shainodev** [MaxXor/xRAT#1239]
### Problem description

I'm just curious as to why Quasar isn't being updated anymore like it was in the previous years?

### Proposal

Idk

**Comment by SiongokBrian** [comment]
Pay a developer to modify it.

**Comment by yankejustin** [comment]
Because software development is a time-intensive process that requires hard-earned knowledge.

It's a popular project but the funding just isn't there. I'd be happy to re-write or update given the funding.

**Comment by Heggeg** [comment]
Why doesn't the developer make a patron channel or something like that so that people can subscribe and support the project

**Comment by MaxXor** [comment]
Because the project is in a gray area I won't accept donations. Best is to support the project by helping to fix bugs and implement new features. To get started I've labeled good first-time issues with 'easy' label found here: https://github.com/quasar/Quasar/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy
