### ISSUE TITLE
New Keylogger Progress

### ISSUE THREAD

**Issue by MaxXor** [MaxXor/xRAT#149]
Hey,
as we don't have a general issue about the new Keylogger, I'll open this one.

What's the current status of the new Keylogger in the `dev-branch`? And is the Keylogger in the `master-branch` stable at the moment?

This is mostly for @yankejustin and @d3agle, as they've worked on the new Keylogger.

Thanks!

**Comment by d3agle** [comment]
I've been working for a while on this and I've got a working solution. However, there is a lot of work that needs to be done.  One of the problems is how the keys will be logged to ensure that the additional enhancements that were desired, are met.  I've fell short of coming up with a viable solution to controlling the situations of displaying Modifier keys e.g. [ctrl + alt + shift + esc].  I feel like this is a problem @yankejustin could tackle with ease.

The current keylogger in the master-branch is stable, but it is not optimized nor is it viable.

Would you like me to commit a bare-bones version of the current work I've done, to the dev branch?

**Comment by MaxXor** [comment]
Yes, that would be great if you make a pull request.

**Comment by MaxXor** [comment]
Bugs: Thread doesn't exit when disabling the hook, has something to do with message pump I believe

Todo: handle modifier keys in another manner. for example a user presses control, and while control is down the user decides to press a, the log will display [CTRL][CTRL + a]

**Comment by yankejustin** [comment]
@d3agle I would appreciate a pull request to be sent to the dev branch. I noticed you made many changes but I don't often send contributions to volatile branches so I was just waiting a little bit on you to add your changes to the new branch.

**Comment by yankejustin** [comment]
@MaxXor Is there a possibility that you could close the issues related to the keylogger on the main branch and open them on the dev branch for us please?

**Comment by yankejustin** [comment]
To give a more definite answer to all those wandering, I have been experimenting with the hook with progress, but I am actually having my High School graduation banquets and such so I have been quite busy! x)
I have time tonight and I will finally switch this thing over to a hook. :)

**Comment by MaxXor** [comment]
@yankejustin Closed them. Congrats for finishing High School! :) No need to rush the code now, take the time you need.

**Comment by yankejustin** [comment]
@MaxXor Haha thanks.
I have a big favor... Would you please resolve some of the conflicts we have with the <code>master</code> branch compared to the <code>dev</code> branch? I am still rather new to doing that using Github so I might end up butchering it. x)

**Comment by MaxXor** [comment]
Done. :)

**Comment by yankejustin** [comment]
Thank you very much!

**Comment by yankejustin** [comment]
@MaxXor I was messing with ideas that have finally come together about this Keylogger. Before I set to work putting the puzzle together (features of handling mouse input, repeated strokes, accent character handling, (alt + key code) combining) I naturally set off to research if anybody has already added a feature like this. It is rather foolish to re-invent the wheel, right? ;)
Anyways, I have stumbled upon a project recently moved to Github and I think it is <b>perfect</b> for our needs.
<h3><a href="https://github.com/gmamaladze/globalmousekeyhook">Link to @gmamaladze's project</a></h3>
It will be very easy to adapt to this project, it is event-driven (no manual Timers), and I know exactly how to fix it up. What is in that project is a good representation of the building blocks for of a functional, efficient, and versatile Keylogger. I could implement this (<i>awaiting gmamaladze's explicit permission</i>) and chain a variant of a producer-consumer pattern to route the output however we wish, and I also expect to hook up my key filter (client can be explicity told which keys to log).

**Comment by d3agle** [comment]
Nice find @yankejustin! I took a look at some of the source and it is very well written. The key filtering will be very important to accomplishing what we need done.  Looking forward to seeing what you can do with this.

**Comment by yankejustin** [comment]
To extend on key filtering, gmamaladze's project also seems to have started on registering hotkeys. For those reading this that may not understand, hotkeys allow filtering of more complex combinations of keys. :)

**Comment by MaxXor** [comment]
Indeed, a very nice find @yankejustin! Hope we can use it too.

**Comment by DragonzMaster** [comment]
nice find, I hope gmamaladze does not mine using his project
I gave it a look and it seems good

**Comment by yankejustin** [comment]
@DragonzMaster It is not possible using .NET... It is possible by invoking native code.

**Comment by yankejustin** [comment]
I suspect an issue in setting the windows hook (preventing output):
https://github.com/yankejustin/xRAT/blob/Keylogger/Client/Core/Keylogger/WinApi/HookHelper.cs#L57
Can someone please help me research how effective getting the current process' main module -> base address is when the process is running under the way the client is? (shell execute = true... etc.)

**Comment by d3agle** [comment]
@yankejustin, the reason the hook isn't working currently is because we don't have a message pump on the thread, so we can't intercept the messages from the OS

Calling Application.Run() should do the trick

**Comment by DragonzMaster** [comment]
i don't know if you have seen this if not you can give a look at the Author's Article you might find it useful
 GlobalHook [http://www.codeproject.com/Articles/7294/Processing-Global-Mouse-and-Keyboard-Hooks-in-C]

**Comment by yankejustin** [comment]
@DragonzMaster Yes, of course I have seen that. :)
The code I have implemented to the keylogger branch is the work of George "gmamaladze"Mamaladze. His updated work is now placed on Github. The link to his repository can be found on a post I made yesterday on this same issue. :goat:

**Comment by yankejustin** [comment]
@d3agle Thank you for the information. It is very appreciated.

**Comment by DragonzMaster** [comment]
i know that the project started on codeproject then to codeplex and finaly to github (a few weeks ago)
but i expect it would help as there is FAQ and comments below
sorry i don't have time to read them nor the project ... i hope that i can help you

**Comment by yankejustin** [comment]
<h1>Status</h1><h4><i>4/22/15</i></h4>
Functioning (<i>needs a bit more work, but <b>it works</b></i>).
<br />
<h1>Upcoming</h1><h4><i>To Finish By 5/24/15</i></h4>
1) Write unit tests for the Keylogger.
2) Perhaps extend supported keys for the Keylogger by attempting to use the (older) <code>KeyloggerKeys</code> enumeration instead of the <code>Keys</code> enumeration.
3) Final testing
<h4><i>By 5/25/15</i></h4>
1) Integration testing
2) Hopefully integrate to <code>master</code>

**Comment by MaxXor** [comment]
I really like your status posts, thanks alot. :) I'll see if I can help with any of this.

**Comment by yankejustin** [comment]
<h1>Status</h1>
Very good point; it works at a <i>very good</i> level.

<h1>To-Do</h1>
At this point, the code is clean and efficient enough to implement to <code>master</code> now. However, we should <b>really</b> fix that vulnerability caused by this before merging. Besides that, the features that are being conjured can come at some later time; for now, this Keylogger is so much better that, besides the vulnerability that has existed since the beginning, it would be a great addition to the <code>master</code> branch.

**Comment by yankejustin** [comment]
Thank you for the complement, MaxXor. :)

**Comment by d3agle** [comment]
I would just like to point out, that before this should be merged to the master branch, we should also take care of the problem with the message pump calling Application.Run().  I haven't found a solution to ending it's operations.  Calling Application.ExitThread() within the thread does not work, and because the thread does not exit, the client won't respond well to disconnects or uninstalling.  I'll try to dig a little bit further to see what else can be done, but I would appreciate any help implementing some sort of solution, whether its clean or not!

**Comment by MaxXor** [comment]
I'll try to find a solution for this too.

**Comment by rabbitsmith** [comment]
can i know what is the vulnerability

**Comment by MaxXor** [comment]
https://github.com/MaxXor/xRAT/issues/167
It's already fixed.

**Comment by d3agle** [comment]
#178, fixed message loop termination

**Comment by d3agle** [comment]
<h1>Status</h1>

<p>Functional and operational</p>

<h1>To-Do</h1>

<p>The keylogger has been refactored and optimized to the point I can hardly find any more ways to improve the functionality.  The only thing left to do at this point seems to be adding more keys e.g. (PageUp, VolumeUp, VolumeDown, etc..) to the HighlightSpecialKeys method for better display.</p>

**Comment by MaxXor** [comment]
@d3agle the PageUp and VolumeUp are already highlighted with the latest commit.

**Comment by d3agle** [comment]
Oh ok! I wasn't sure I hadn't tested them I was just using them as examples for extra keys to add.  We should really add as many as we can just so we can ensure it looks pretty on the user-end :D

**Comment by MaxXor** [comment]
When we find the reason for issue #181 and fix it, we can merge `dev` into `master`.

**Comment by MaxXor** [comment]
<h1>Status</h1>
* Fully functional and operational
* Ready to merge into `master`

**Comment by d3agle** [comment]
Before merging this @MaxXor, I need to fix a bug with the dead-keys.  Pressing the ^ key then Shift + character should produce an upper-case accented character

**Comment by d3agle** [comment]
dead-key fix #189

**Comment by d3agle** [comment]
Another bug surfaced, it has to do with how we handle our modifier keys.

![](http://puu.sh/hYCFq/61010173cc.png)

**Comment by yankejustin** [comment]
@d3agle Out of curiosity, what is your keyboard layout?

**Comment by d3agle** [comment]
@yankejustin, I'm using German keyboard layout.  (Layout pack DEU) http://clasfaculty.ucdenver.edu/tphillips/GermanKeyboardLayout.html

**Comment by yankejustin** [comment]
I am on a different machine that supports different characters.
Here is a short list of some good (common) specials to test for:
` ¡ ™ £ ¢ ∞ § ¶ • ª º – ≠
œ ∑ ´ ® † ¥ ¨ ˆ ø π “ ‘ «
å ß ∂ ƒ © ˙ ∆ ˚ ¬ … æ 
Ω ≈ ç √ ∫ ˜ µ ≤ ≥ ÷

**Comment by d3agle** [comment]
Another problem is that some of the accented characters, for example 'Ê' (pressing '^' followed by shift + e), will provide the correct representations from the system, but in our logs it will state a 'E' without the accents.  This doesn't happen with lowercase letters.  Perhaps there is something that happens when converting the character values to strings?

**Comment by yankejustin** [comment]
https://github.com/d3agle/xRAT/blob/dev/Client/Core/Keylogger/WinApi/KeyboardNativeMethods.cs#L318
Does using <code>Charset.Auto</code> affect us? Shouldn't we specify to marshal the info. using <code>Charset.Unicode</code>?
Also, @d3agle , I would find where our flags are internally being reset somewhere along the lines...
I would also recommend actually looking at the actual logs and making sure it is not an issue with displaying it in the WebBrowser control.

**Comment by d3agle** [comment]
@yankejustin, I'm not sure.  I will check it out and see if I can produce some results.  Also, the ToUnicodeEx method in https://github.com/MaxXor/xRAT/blob/dev/Client/Core/Keylogger/WinApi/KeyboardNativeMethods.cs#L77 will report the correct unicode value.  However, in the raw data in the KeyPress event, the e.KeyChar value will be of unaccented value (Given the state of holding 'shift + key').  The webbrowser control won't be the problem since I've added the metadata tags for displaying utf-8 charsets

**Comment by yankejustin** [comment]
https://github.com/MaxXor/xRAT/blob/dev/Client/Core/Keylogger/WinApi/KeyboardNativeMethods.cs#L141
Try <code>while (rc < 1);</code>

**Comment by yankejustin** [comment]
https://github.com/MaxXor/xRAT/blob/dev/Client/Core/Keylogger/WinApi/KeyboardNativeMethods.cs#L118
Restrict how often that is set to 0. We should not lose that <code>lastVirtualKeyCode</code> so fast... :(

I'm curious why there is a return type <code>bool</code> on this function; it will always return <code>true</code>.

**Comment by d3agle** [comment]
@yankejustin , I fixed this about an hour ago #189, the system posts the message to the active window with success an accurately, it's only when its translated back into a character we don't have the data

Also, you're right, the return type doesn't matter.  I had to make some modifications to the code to get it to work and I didn't think about changing the method to void.  The only thing we are interested in getting out of this method is the char[]

**Comment by yankejustin** [comment]
Before I leave for a bit, I just wanted to clarify what I said earlier.
There is a location within that method (likely somewhere around where I suggested) that is obviously setting an internal state incorrectly, causing the reflected output to be something that is <b>not</b> what went in. Somewhere along the lines, it is either setting the incorrect internal state or is neglecting to handle it.
Last lead before I go:
https://github.com/MaxXor/xRAT/blob/dev/Client/Core/Keylogger/WinApi/KeyboardNativeMethods.cs#L110
<b>Possibility</b>
It is often very likely that it arrives at that case when there are two or more items found <b><i>because of un unresolvable dead key combination</i></b>.
It is likely arriving there because https://github.com/MaxXor/xRAT/blob/dev/Client/Core/Keylogger/WinApi/KeyboardNativeMethods.cs#L118 is losing our value of the lastVirtualKeyCode, and is telling the rest of the method that it is <b>not</b> to be handled as a dead key (even though it likely was).

**Comment by yankejustin** [comment]
Oh, got it. I will see this again later if it is not fixed. Enjoy your day.

**Comment by d3agle** [comment]
Thanks.  You too!  When you're available, it would be awesome if you could brainstorm some alternate modifier key designs so we can use (AltGr modifier - which is (Ctrl + alt) but also provides a character)

**Comment by d3agle** [comment]
@yankejustin, thank you for pointing this out! I have fixed the accenting bug now!

The only thing that appears that is left to do is modify our ModifierKeys design to something that will allow us to use the AltGr modifier (Ctrl + alt + key) as a character representation!

**Comment by d3agle** [comment]
Reference to this problem: 
(The line that is inaccurate with the ^^, I'm not sure why this happens. Press the '^' dead key once then again and it will display ^^ as it would normally, however in our logs it displays once (not applying the dead key as a character)

The problem is the raw event handlers in this case our KeyPress event, the first '^' (caret) is sent to the handler, and added to our pressedKeyChars List, followed by another caret sent to the method after.  Since its already added it wont be added again/added to the logs.  We definitely need a new design other than using Lists to detect multiple keypresses

**Comment by MaxXor** [comment]
Fixed the bug with the ^^. :)

**Comment by MaxXor** [comment]
<h1>Status</h1>
* All known bugs have been fixed
* Ready to merge into `master`

**Comment by d3agle** [comment]
Awesome :) Good job!

We can merge this into master if you are ready to, however we still need to work on modifier keys.

For example, try pressing AltGr and a key to display a symbol, then look at the logs

**Comment by MaxXor** [comment]
Sorry, I've updated the status. I'll look into this.

**Comment by DragonzMaster** [comment]
but one thing need to be added >> the time to windows title @d3agle @MaxXor

**Comment by d3agle** [comment]
@DragonzMaster , good call!

**Comment by xmizrx** [comment]
Good job you guys ...
the purpose of a key-logger is to log every key that have bean pressed on
the keyboard nothing more ... but since the data will be huge some times
its harder to read the raw data ... so I think you should work on a filter
so that data can be easier to read like this picture below


here is the source

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

namespace xServer.Forms
{
    public partial class FrmRePlay : Form
    {
        public FrmRePlay()
        {
            InitializeComponent();
        }
        private int i;
        private string strMessage;

        private void start_Click(object sender, EventArgs e)
        {
            string str;
            string str1;
            str1 = "";
            str = in1.Text;
            while (((str.IndexOf("[Back]") + 1)
                        != 0))
            {
                str1 = str.Substring((str.IndexOf("[Back]") + 6));
                str = fun(str.Substring(0, str.IndexOf("[Back]")));
                str = (str + str1);
            }
            in2.Text = str;
            //  will give the output
            i = 0;
            TextReplay.Text = "";
            timer1.Enabled = true;
            strMessage = in2.Text;
        }

        private void stop_Click(object sender, EventArgs e)
        {
            timer1.Stop();
        }
        public string fun(string str)
        {
            return str.Remove((str.Length - 1), 1);
        }

        private void timer1_Tick(object sender, EventArgs e)
        {
            i++;
            TextReplay.Text = (TextReplay.Text + strMessage.Substring((i -
1), 1));
            if ((i == strMessage.Length))
            {
                timer1.Enabled = false;
            }
            if (strMessage.Contains("[Enter]"))
            {
                strMessage = strMessage.Replace("[Enter]", "\r\n");
            }
        }

        private void FrmRePlay_Load(object sender, EventArgs e)
        {
            in1.Text = Clipboard.GetText();
            string str;
            string str1;
            str1 = "";
            str = in1.Text;
            while (((str.IndexOf("[Back]") + 1)
                        != 0))
            {
                str1 = str.Substring((str.IndexOf("[Back]") + 6));
                str = fun(str.Substring(0, str.IndexOf("[Back]")));
                str = (str + str1);
            }
            in2.Text = str;
            //  will give the output
            i = 0;
            TextReplay.Text = "";
            timer1.Enabled = true;
            strMessage = in2.Text;
        }
    }
}

**Comment by d3agle** [comment]
@xmizrx , that is a nice idea.  Maybe you can add an enhancement for this when we have completed it, kind of like an add-on for the Log viewer for the server!

**Comment by DragonzMaster** [comment]
but don't forget to ignore special keys (ex escape, up, down, volume ...... etc)

**Comment by yankejustin** [comment]
Personally, I think we should add this to <code>master</code> now. It is so significantly better than the original keylogger that (because the keylogger in the <code>dev</code> branch has no more major issues) it is up to a polishing point. This should be implemented now and allow the long "polishing" phase to tie with the <code>master</code> branch.

**Comment by d3agle** [comment]
@yankejustin , sorry I broke it XD.  take a look at #190.  After this I think it SHOULD be good to go, I'm currently testing other possibilities/scenarios with other languages/keyboard layouts that use dead-keys.  If I can't break it after I spend a few more hours with it we should be good to go!

**Comment by yankejustin** [comment]
@MaxXor Next branch created for <code>dev</code> should be on the next priority: <b>persistence</b>.

**Comment by DragonzMaster** [comment]
Presistance OR Registry Editor :thought_balloon:  ?? @yankejustin

**Comment by yankejustin** [comment]
Registry Editor is a minor feature. By minor, I mean that (<i>please</i> tell me if I am incorrect) the process of creation and implementation is rather straight forward. I do not think editing a registry hive by a programming language is difficult. Not much different than a file editor. :)
I will look into it while MaxXor deliberates on the next priority.

**Comment by rabbitsmith** [comment]
@yankejustin please describe the status of the keylogger so that useless and good-for-nothing people like me can understand

**Comment by d3agle** [comment]
@MaxXor, as @yankejustin said this is good to go
