### ISSUE TITLE
New Keylogger chars like ^ or ` not working

### ISSUE THREAD

**Issue by MaxXor** [MaxXor/xRAT#181]
To reproduce this issue run the client with keylogger enabled and press ^ (under Escape).

**Comment by DragonzMaster** [comment]
`~`~
++=_-)0(9*8&7^6%5$4#3@2!1~`~`
------------------------------------------------------
the above is what i wrote to test the keylogger and it seems to work for me :D
![kel2](https://cloud.githubusercontent.com/assets/12255107/7785013/e9741b90-017c-11e5-9f32-80b6f962cd8b.png)

**Comment by d3agle** [comment]
This is working for me as well.  What kind of keyboard do you have?  Under my escape key is the tilde key (OemTilde)

**Comment by d3agle** [comment]
@MaxXor, took a look here: http://clasfaculty.ucdenver.edu/tphillips/GermanKeyboardLayout.html

"The characters ² ³ { [ ] } \ @ € µ ~ are accessed by holding the Alt Gr key and tapping the other key. 
The Alt key on the left will not access these additional characters.
The accent keys ^ ` ´ are dead keys (nothing happens until you type a second key).
Tap on an accent key once, let up, then tap on a vowel to produce accented characters. (ô á ù etc.)
Note that the semi-colon and colon are accessed by holding down the shift key (large arrow up)."

**Comment by d3agle** [comment]
Because these are dead keys, they won't be processed.  Take a peek at the method at line 73 ('xClient.Core.Keyloggers.WinApi.KeyboardNativeMethods')

**Comment by DragonzMaster** [comment]
why should i use the last commit !!
the keylogger already works fine for me
but github doesn't show ' ~ when there are no spaces between them, instead it shows them like that '~
so every key i have pressed is logged correctly @d3agle

**Comment by d3agle** [comment]
@DragonzMaster , haha sorry!

**Comment by DragonzMaster** [comment]
no problem bro
I hope you find a fix for @MaxXor problem

**Comment by MaxXor** [comment]
lol yea I press ^ once and then again to show it, works fine without the keylogger. :(

**Comment by d3agle** [comment]
@MaxXor , When you say it works fine without the keylogger, do you mean that with the keylogger enabled and the client running, your ^ key doesn't function as it would without the keylogger enabled?

**Comment by MaxXor** [comment]
Correct.

**Comment by d3agle** [comment]
Oh boy.  I will look into this, that doesn't sound good

**Comment by d3agle** [comment]
@MaxXor , could you try something for me?  I don't have a german keyboard to test this on, but I wonder if the dead key has a state that is being reset the first time you press it.  I noticed that sometimes when starting the client with keylogger enabled, keys would be reset if they were already enabled.  For example, if I had Numlock toggled off prior to starting the client, when I pressed Numlock to turn it on, it would turn it off as soon as i pressed and released it.  I have a feeling this could be due to clearing the keyboard buffer in https://github.com/MaxXor/xRAT/blob/dev/Client/Core/Keylogger/WinApi/KeyboardNativeMethods.cs#L85.


Could you try using the key multiple times, to ensure the keyboard buffer is cleared by the time you next press your dead key?  For example, Try accenting some characters a few times and see what it outputs.

**Comment by MaxXor** [comment]
I did what you said, but it didn't work. I'll try removing this line and see what happens. :D

**Comment by d3agle** [comment]
Thanks!  I just realized, someone recently raised this issue with the programmer who wrote this library, and he claims to have fixed it.  I wonder if the problem is with our logic?

https://github.com/gmamaladze/globalmousekeyhook/issues/4

**Comment by MaxXor** [comment]
Thanks, I've read it. Urutar also said it's not gone yet. :D Let's see if he can fix it!

**Comment by d3agle** [comment]
Sent a pull request with some fixes, along with a possible dead-key fix. #186, needs to be tested!

**Comment by d3agle** [comment]
Tested on Windows 8 VM with success!

![](http://puu.sh/hYbya/6dda3185f0.png)
