### ISSUE TITLE
keylogger

### ISSUE THREAD

**Issue by DragonzMaster** [MaxXor/xRAT#80]
why you have removed F1:F12 Keys
is there any solution to get them handled ?

**Comment by d3agle** [comment]
The reason they were removed is because each key that we want to log should have some sort of character(s) to show for it in the logs.  The f1-f11 keys weren't printing anything to the log and the way the active window title headers are written, it would leave blank characters to follow and it takes up unnecessary space

**Comment by DragonzMaster** [comment]
thnx for your time
i think that can be possible by changing the value to Key type then you can handle it (using If or Select Case ) and log it as [F1] etc
